name: Build project
run-name: ${{ github.actor }} is building the app...
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      failed: ${{ steps.build.outputs.exit_code }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build
        id: build
        run: |
          npm ci 
          npm run build
      - name: Deploy to github pages
        if: github.ref == 'refs/heads/main'
        id: deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
