name: Build project
run-name: ${{ github.actor }} is building the app...
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: |
          npm ci 
          npm run build
